### PR TITLE
Add landing-info section [OC-107]

### PR DESCRIPTION
**Pull request by samanehsan**
- Add address field to meeting create and update forms
- Add section that displays meeting date, location and address.

screen shot 2017-07-20 at 5 05 44 pm

### CODE REVIEW

**Comment by cameronblandford** [comment]
Looks good! Do we want to include the option to specify an address as well?

**Comment by samanehsan** [comment]
> Should there be a way to display the precise address of the meeting in this component?

I think that would be a good addition! For now, do you think adding the address to the item model as a string field would work? Storing all of the address info separately and piecing it together in the right format may get complicated if you consider international addresses.

**Comment by cameronblandford** [comment]
String sounds like a good representation for now!

**Comment by cameronblandford** [comment]
Looks great!

**Pull request merged**
