### PR TITLE
Add table view to file grid

### PR DESCRIPTION
**Pull request by cameronblandford**
screenshot 2017-11-06 15 37 10
screenshot 2017-11-06 15 37 04

### CODE REVIEW

**Comment by birdbrained** [comment]
shoul the two buttons on the right habnd side be so far in?

**Comment by Rytiggy** [comment]
Looks awesome

**Comment by cameronblandford** [comment]
they shouldn't, u right

**Comment by Rytiggy** [comment]
really looks good this time

**Pull request merged**
