### PR TITLE
Add filtering to presentation list [OC-119]

### PR DESCRIPTION
**Pull request by samanehsan**
Add filtering presentation list by title, author or by event type:  
screen shot 2017-08-02 at 2 07 39 pm

### CODE REVIEW

**Comment by cameronblandford** [comment]
Are we going to keep status as a visible field, and if so, should it be sortable? Otherwise, looks good!

**Comment by samanehsan** [comment]
> Are we going to keep status as a visible field, and if so, should it be sortable?

I think the status would be useful information for admins. However, there's no interface for them to change the status so we could hide it until it becomes relevant. What are your thoughts @cameronblandford?

**Comment by cameronblandford** [comment]
I think hiding it until it becomes relevant makes the most sense!

**Comment by samanehsan** [comment]
Done making that change @cameronblandford!

**Comment by cameronblandford** [comment]
Looks good! Merging

**Pull request merged**
