### PR TITLE
Hide edit ui when user is logged our [OC-64] 

### PR DESCRIPTION
**Pull request by caneruguz**

### CODE REVIEW

**Comment by samanehsan** [comment]
I can still see the "Edit" and "Add content" tabs when I'm logged out of collections: 

screen shot 2017-06-02 at 4 29 44 pm

**Comment by samanehsan** [comment]
Also the "Start a collection" button should only be visible to logged in users: 

screen shot 2017-06-02 at 4 30 46 pm

**Comment by samanehsan** [comment]
Done with first-pass review @caneruguz! :octocat:

**Comment by caneruguz** [comment]
@samanehsan  Thanks, the last commit should take care of three more areas 
- navigation links you mentioned
- "start a collection" button
- "Add to collection" buttons in landing pages

**Comment by samanehsan** [comment]
Thanks for making those changes @caneruguz! I just noticed the "Customize your landing page" message is still visible to logged in users. It should only be visible to users who can edit the collection settings:  

screen shot 2017-06-05 at 10 22 30 am

**Comment by birdbrained** [comment]
Is this good to go then?

**Comment by caneruguz** [comment]
@samanehsan @birdbrained  should be good to merge now

**Comment by samanehsan** [comment]
Thanks! ☔️

**Pull request merged**
